### ISSUE TITLE
Need to handle message deletions better

### ISSUE THREAD

**Issue by tdmalone** [tdmalone/slack-topic-updater#1]
There's more to add here, but just adding the error now so I don't lose it

```
Oct 17 11:19:37 ops-team-topic-updater app/web.1:  (node:4) UnhandledPromiseRejectionWarning: Error: An API error occurred: message_not_found 
Oct 17 11:19:37 ops-team-topic-updater app/web.1:      at platformErrorFromResult (/app/node_modules/@slack/client/dist/WebClient.js:769:42) 
Oct 17 11:19:37 ops-team-topic-updater app/web.1:  (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2) 
Oct 17 11:19:37 ops-team-topic-updater app/web.1:  (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
Oct 17 11:19:37 ops-team-topic-updater app/web.1:  (node:4) UnhandledPromiseRejectionWarning: Error: An API error occurred: message_not_found 
Oct 17 11:19:37 ops-team-topic-updater app/web.1:      at platformErrorFromResult (/app/node_modules/@slack/client/dist/WebClient.js:769:42) 
Oct 17 11:19:37 ops-team-topic-updater app/web.1:  (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4) 
```

**Comment by tdmalone** [comment]
So basically, this error is encountered when trying to delete a topic update message that doesn't exist.

This can happen when multiple invocations occur at once, and messages are already deleted by another invocation before the current one manages to get to them (listing and deleting messages isn't an atomic action).

Therefore, it's likely to be quite safe to explicitly catch this error and do nothing. The worst that could happen is a topic update message somehow gets left around... which we obviously don't want to occur, but at least it's not that bad!
